name: python-coverage 

on: 
    workflow_dispatch:

jobs:
    start:
        name: Post next step content
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v5

            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                python-version: 3.13

            - name: Install dependencies
              run: |
                    pip install -r requirements.txt
                    pip install pytest==8.4.1
                    pip install coverage==7.9
                    pip install pytest-cov==6.2.1

            - name: Test with pytest
              run: |
                pytest --verbose